import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { ChevronDown, Check, Loader2, Circle, Download, FileText, Paperclip } from "lucide-react";
import type { ChatMessage, TimelineMessage, FileMessage, DownloadMessage, TextMessage, InputCardMessage } from "@/lib/chat-types";
import { InputCard } from "./InputCard";

export function MessageItem({ msg }: { msg: ChatMessage }) {
  const isUser = msg.role === "user";
  if (isUser) {
    return (
      <div className="flex justify-end px-4 py-2">
        <div className="max-w-[78%]">
          {msg.type === "text" && (
            <div className="rounded-2xl rounded-br-md bg-bubble-user px-4 py-2.5 text-sm text-bubble-user-foreground">
              {(msg as TextMessage).content}
            </div>
          )}
          {msg.type === "file-upload" && <UserFileBubble msg={msg as FileMessage} />}
        </div>
      </div>
    );
  }

  // Bot side – no background, full width content
  return (
    <div className="px-4 py-3">
      <div className="mx-auto flex max-w-3xl gap-3">
        <div className="mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-primary/15 text-primary text-[11px] font-bold">
          A
        </div>
        <div className="min-w-0 flex-1">
          {msg.type === "text" && <BotText msg={msg as TextMessage} />}
          {msg.type === "timeline" && <Timeline msg={msg as TimelineMessage} />}
          {msg.type === "input-card" && <InputCard msg={msg as InputCardMessage} />}
          {msg.type === "download" && <DownloadCard msg={msg as DownloadMessage} />}
        </div>
      </div>
    </div>
  );
}

function BotText({ msg }: { msg: TextMessage }) {
  return (
    <div className="md text-[15px] leading-relaxed text-foreground">
      <ReactMarkdown>{msg.content}</ReactMarkdown>
    </div>
  );
}

function UserFileBubble({ msg }: { msg: FileMessage }) {
  return (
    <div className="rounded-2xl rounded-br-md bg-bubble-user px-3 py-2.5 text-sm text-bubble-user-foreground space-y-2">
      {msg.files.map((f) => (
        <div key={f.id} className="flex items-center gap-2 rounded-lg bg-background/10 px-2 py-1.5">
          <Paperclip className="h-3.5 w-3.5 opacity-80" />
          <div className="min-w-0 flex-1">
            <div className="truncate text-xs font-medium">{f.name}</div>
            <div className="text-[10px] opacity-70">{(f.size / 1024).toFixed(1)} KB</div>
          </div>
        </div>
      ))}
      {msg.note && <div>{msg.note}</div>}
    </div>
  );
}

function Timeline({ msg }: { msg: TimelineMessage }) {
  const [open, setOpen] = useState(true);
  const active = msg.steps.find((s) => s.status === "active");
  return (
    <div className="rounded-2xl border border-border bg-card/60">
      <button
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center gap-2 px-3 py-2.5 text-sm font-medium"
      >
        {msg.done ? (
          <Check className="h-4 w-4 text-primary" />
        ) : (
          <Loader2 className="h-4 w-4 animate-spin text-primary" />
        )}
        <span>{msg.title}</span>
        {active && !msg.done && (
          <span className="text-xs font-normal text-muted-foreground">· {active.label}</span>
        )}
        <ChevronDown className={`ml-auto h-4 w-4 text-muted-foreground transition ${open ? "" : "-rotate-90"}`} />
      </button>
      {open && (
        <ol className="space-y-2 border-t border-border px-4 py-3 text-sm">
          {msg.steps.map((s) => (
            <li key={s.id} className="flex items-center gap-2.5">
              {s.status === "done" ? (
                <Check className="h-3.5 w-3.5 text-primary" />
              ) : s.status === "active" ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin text-primary" />
              ) : (
                <Circle className="h-3 w-3 text-muted-foreground/60" />
              )}
              <span className={s.status === "done" ? "text-muted-foreground line-through" : s.status === "active" ? "text-foreground" : "text-muted-foreground"}>
                {s.label}
              </span>
            </li>
          ))}
        </ol>
      )}
    </div>
  );
}

function DownloadCard({ msg }: { msg: DownloadMessage }) {
  const downloadFile = () => {
    // mock file
    const blob = new Blob([`Mock content of ${msg.fileName}\nGenerated by Agent.`], {
      type: msg.mime || "text/plain",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = msg.fileName;
    a.click();
    URL.revokeObjectURL(url);
  };
  return (
    <div className="flex items-center gap-3 rounded-2xl border border-border bg-card p-3 shadow-sm">
      <div className="grid h-11 w-11 place-items-center rounded-xl bg-primary/15 text-primary">
        <FileText className="h-5 w-5" />
      </div>
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-medium">{msg.title}</div>
        <div className="truncate text-xs text-muted-foreground">
          {msg.fileName}{msg.sizeLabel ? ` · ${msg.sizeLabel}` : ""}
          {msg.description ? ` · ${msg.description}` : ""}
        </div>
      </div>
      <button
        onClick={downloadFile}
        className="flex shrink-0 items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-xs font-medium text-primary-foreground hover:opacity-90"
      >
        <Download className="h-3.5 w-3.5" /> Download
      </button>
    </div>
  );
}

export function TypingIndicator() {
  return (
    <div className="px-4 py-3">
      <div className="mx-auto flex max-w-3xl gap-3">
        <div className="mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-primary/15 text-primary text-[11px] font-bold">A</div>
        <div className="flex items-center gap-1 pt-2">
          <span className="typing-dot" />
          <span className="typing-dot" />
          <span className="typing-dot" />
        </div>
      </div>
    </div>
  );
}
